list = [1,2,3,4,5,]
list2 = [7,8,9,10]
print(f"List : {list} ")
print(f"List2 : {list2} ")
print("\n")
print(f"Length of list : {len(list)}")
print(f"Max element in list : {max(list)}")
print(f"Min element in list : {min(list)}")
print(f"Sum of list : {sum(list)}")
print(f"List*3 : {list*3}")
print(f"1 in List? : {1 in list}")
print(f"6 not in List? : {6  not in list}")
print(f"Append 6 : {list.append(6)}")
print(f"Extend list : {list.extend(list2)}")
print(f"Insert 0 at 0 index : {list.insert(0,0)}")
print(f"Remove 10 : {list.remove(10)}")
print(f"Pop : {list.pop()}")
print(f"Count : {list.count(1)}")
print(f"Reverse : {list.reverse()}")
print(f"Sort : {list.sort()}")
print(f"Index of 0 : {list.index(0)}")
list3=list.copy()
print(f"Copy first list into another and print it : {list3}")
